### ISSUE TITLE
why easy to be ANR in android 4.4?

### ISSUE THREAD

**Issue by wb12581** [Krupen/AutoplayVideos#1]

**Comment by Krupen** [comment]
I tried it in emulator with 256MB RAM but was not able to produce ANR. 
I released an update(0.0.5) that fixes a crash in pre-lollipop devices, let me know if the update fixed the crash for you.

**Comment by Krupen** [comment]
I hope you are not getting this issue post version 0.0.5. Also if you have too many videos in your list, try to implement pagination and load 10-15 videos a time to resolve OutOfMemory issues. Closing this for now, reopen it if you still face this issue.
