### ISSUE TITLE
Blank RecyclerView is showing.

### ISSUE THREAD

**Issue by ashish1988** [Krupen/AutoplayVideos#10]
I have integrated this library, project build and run successfully but the RecyclerView is empty.
![empty_recycler_view](https://cloud.githubusercontent.com/assets/26221013/24246415/365e74ac-0fed-11e7-8799-5af13b1153fb.png)

**Comment by Krupen** [comment]
can you share code of how you have set up the library in your project?

**Comment by ashish1988** [comment]
**Build.gradle**

```
dependencies {
     compile 'com.allattentionhere:autoplayvideos:0.0.4'
}
```

**RecyclerView item layout [videos_grid_row.xml]**

`<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:orientation="vertical">

    <RelativeLayout
        android:id="@+id/galleryGridBackground"
        android:layout_width="@dimen/video_size_in_grid"
        android:layout_height="@dimen/video_size_in_grid"
        android:layout_centerHorizontal="true"
        android:background="@drawable/image_boundary"
        android:paddingBottom="@dimen/galley_grid_padding_top_bottom"
        android:paddingLeft="@dimen/galley_grid_padding_left_right"
        android:paddingRight="@dimen/galley_grid_padding_left_right"
        android:paddingTop="@dimen/galley_grid_padding_top_bottom">

        


        <com.allattentionhere.autoplayvideos.AAH_VideoImage
            android:layout_width="220dp"
            android:layout_height="220dp" />

    </RelativeLayout>

    <ImageView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_centerInParent="true"
        android:src="@drawable/ic_play_video" />

</RelativeLayout>`

**RecyclerView Adapter [VideosGridAdapter.java] **

`package com.roam.life.adapters;

import android.app.Activity;
import android.graphics.Bitmap;
import android.media.MediaMetadataRetriever;

import android.os.AsyncTask;
import android.os.Build;

import android.view.LayoutInflater;
import android.view.TextureView;
import android.view.View;
import android.view.ViewGroup;


import com.allattentionhere.autoplayvideos.AAH_CustomViewHolder;

import com.allattentionhere.autoplayvideos.AAH_VideosAdapter;
import com.roam.life.R;

import com.roam.life.common.Common;
import com.roam.life.datamodel.VideoDataModel;

import java.util.HashMap;
import java.util.List;


/**
 * Created by atiwari on 21/3/17.
 */

public class VideosGridAdapter extends AAH_VideosAdapter {

    private Activity activity;
    private List<VideoDataModel> videosList;
    private int[] galleryGridBackground = {R.drawable.albumstack1,
            R.drawable.albumstack2, R.drawable.albumstack3,
            R.drawable.albumstack4};

    public VideosGridAdapter(Activity activity, List<VideoDataModel> videosList) {
        this.activity = activity;
        this.videosList = videosList;
    }

    @Override
    public ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {

        LayoutInflater inflater = LayoutInflater.from(parent.getContext());
        View view = inflater.inflate(R.layout.videos_grid_row, parent, false);

        ViewHolder viewHolder = new ViewHolder(view);

        return viewHolder;
    }

    @Override
    public void onBindViewHolder(AAH_CustomViewHolder holder, int position) {
        super.onBindViewHolder(holder, position);


        //load image/thumbnail into imageview
        if (videosList.get(position).getVideoUrl() != null && !videosList.get(position).getVideoUrl().isEmpty()) {
            holder.setVideoUrl(Common.IMAGE_BASE_URL + videosList.get(position).getVideoUrl());
            holder.setImageUrl("https://www.gstatic.com/webp/gallery3/1.png");
        }
    }


    @Override
    public long getItemId(int position) {
        return Long.valueOf(videosList.get(position).getVideoId());
    }

    @Override
    public int getItemCount() {
        return videosList.size();
    }

    @Override
    public int getItemViewType(int position) {
        return 0;
    }

    /**
     * ********************* View Holder *********************************************************
     */

    public class ViewHolder extends AAH_CustomViewHolder {

        public ViewHolder(View itemView) {
            super(itemView);
        }
    }
}
`

**Fragment [VideosFragment.java]**

`public class VideosFragment extends BaseFragment implements AdapterView.OnItemClickListener {

    private AAH_CustomRecyclerView videosRecyclerView;
    private ActionBar actionBar;
    private MessageView mMessageView;
    private LoadingView loadingView;
    private ArrayList<VideoDataModel> mVideosList = new ArrayList<>();
    private VideosGridAdapter adapter;
    private View rootView;

    public static VideosFragment getInstance() {
        return new VideosFragment();
    }

@Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {

        setHasOptionsMenu(true);
        actionBar = ((AppCompatActivity) getActivity()).getSupportActionBar();
        actionBar.setTitle("My Videos");

        if (rootView == null) {
            rootView = inflater.inflate(R.layout.fragment_galleries,
                    container, false);
            videosRecyclerView = (AAH_CustomRecyclerView) rootView
                    .findViewById(R.id.videos_recycler_view);
            loadingView = (LoadingView) rootView.findViewById(R.id.loadingView);
            mMessageView = (MessageView) rootView.findViewById(R.id.messageView);

            GridLayoutManager gridLayoutManager = new GridLayoutManager(getActivity(), 2);
            videosRecyclerView.setLayoutManager(gridLayoutManager);
            videosRecyclerView.addItemDecoration(new SpacesItemDecoration((int) getResources().getDimension(R.dimen.gallery_photo_grid_item_padding)));

            //videosRecyclerView.addItemDecoration();

            if (!commonObj.isNetworkAvailable()) {
                mMessageView.show();
            } else {

                Bundle bundle = getArguments();
                if (bundle != null) {
                    getData(bundle.getString(GalleriesDetailFragment.KEY_PROFILE_ID));
                }

            }
        }

        return rootView;
    }`

**Setting data on API response**

`  if (datas.length > 0) {
                                mVideosList.addAll(Arrays.asList(datas));
                                
                                adapter = new VideosGridAdapter(getActivity(), mVideosList);
                                videosRecyclerView.setActivity(getActivity());
                                videosRecyclerView.setAdapter(adapter);

                                videosRecyclerView.smoothScrollBy(0,1);
                                videosRecyclerView.smoothScrollBy(0,-1);
                                
                            }`

**Comment by Krupen** [comment]
I made a project with grid adapter and it worked perfectly fine for me. 
Project Link: https://drive.google.com/file/d/0Bys36lxF42L8S3B2eFdpTGJUakk/view?usp=sharing
APK link: https://drive.google.com/open?id=0Bys36lxF42L8cXd5MXh5YlhpOGs

Few things that might be causing the videos to not appear:
1.  The url you are setting in `setVideoUrl` method might not be proper url, check it by logging it.
2.  Item decoration might be overlapping the view.
3. Your API call might not be returning.

**Comment by Krupen** [comment]
I hope the problem is solved, if not feel free to re-open this issue.
