### ISSUE TITLE
Horizontal ReyclerView

### ISSUE THREAD

**Issue by yankauskas** [Krupen/AutoplayVideos#13]
It does not work with horizontal layout manager

**Comment by Krupen** [comment]
I tried it and it works well. 
Just make the following changes in sample app to test it:


In MainActivity.java
` LinearLayoutManager mLayoutManager = new LinearLayoutManager(this,LinearLayoutManager.HORIZONTAL,false);
`

` recyclerView.smoothScrollBy(1,0);
        recyclerView.smoothScrollBy(-1,0);`

In single_card.xml
`<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:card_view="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_marginBottom="8dp"
    android:layout_marginTop="8dp"
    android:gravity="center">`

` <com.allattentionhere.autoplayvideos.AAH_VideoImage
                android:layout_width="150dp"
                android:layout_height="150dp" />`

I have also attached sample APK.



[app-debug.apk.zip](https://github.com/Krupen/AutoplayVideos/files/878081/app-debug.apk.zip)

**Comment by Krupen** [comment]
Closing this issue, feel free to re-open if not solved.

**Comment by hardikJoshi123** [comment]
Hello,

 If you set scroll to X index in horizontal RecycleView, video will not play. try it out.

// try by position =5
layoutManager.scrollToPositionWithOffset(Integer.parseInt(position), 0);
