### ISSUE TITLE
Video is playing and scroll listener's first and last complete visible positions are always -1

### ISSUE THREAD

**Issue by MustanserIqbal93** [Krupen/AutoplayVideos#16]
Hi,

I am trying to play videos but it is not working, i tried to figure out the issue and as far as i found is that scroll listener fist and last complete positions are always -1. and that is it not playing any video.

Can you help me to resolve the error.

Thanks

**Comment by Krupen** [comment]
Yes, in this case, your whole Recyclerview item(not just AAH_VideoImage) must not be fitting in a single screen. 

If you still require to play-video when whole Recyclerview item is not completely visible, you can replace `firstCompletelyVisiblePosition ` with `firstVisiblePosition ` and `lastCompletelyVisiblePosition ` with `lastVisiblePosition ` in `AAH_CustomRecyclerView.java` in library. Also comment/remove `((AAH_CustomViewHolder) holder).pauseVideo();` anywhere in that file.

Let me know if this doesn't work for you, I will send you a working sample.

**Comment by MustanserIqbal93** [comment]
Thanks for the reply. then how i will pause the video. because i want to play on video at a time.

**Comment by MustanserIqbal93** [comment]
I will really appreciate if  you can send me working sample because i tried to replace things as you suggested but its not working. Thanks

**Comment by Krupen** [comment]
Hi, please check the below project. Hope that works for you.

https://drive.google.com/file/d/0B5i30XeKjRLNYXNuSmFyME01dVE/view?usp=sharing

**Comment by MustanserIqbal93** [comment]
Thanks @Krupen Sample is working fine 
Last question is two videos are playing at a time. how to avoid playing two videos at a time. 
Thanks

**Comment by Krupen** [comment]
Instead of `for` loop in `AAH_CustomRecyclerView.java` which calls `playVideo()` , just call `playVideo()` on first item of for loop only.

**Comment by Krupen** [comment]
Closing this issue, feel free to re-open if not solved yet.
