### ISSUE TITLE
Does this work in a Fragment?

### ISSUE THREAD

**Issue by IndDev** [Krupen/AutoplayVideos#17]
Hi I am relatively new to android, and was trying to implement this inside a fragment. From my novice analysis, it seems that the recyclerview directly works on an Activity.  Any chance I can get this working in a fragment? 

Thanks!

**Comment by Krupen** [comment]
Yes it will work in Fragments. Just call all the functions in Fragment which I am calling in Activity. 
And don't forget to setActivity by calling ` recyclerView.setActivity(getActivity());` before setting adapter.
