### ISSUE TITLE
Not able to play mp4 hosted at amazon server. Application hangs

### ISSUE THREAD

**Issue by Hemant0812** [Krupen/AutoplayVideos#18]
First of all a great work. It worked very well with the URL's given in the demo application but when i tried to play videos and load images from amazon s3 server, the application hanged. I tried to reduce down the size  to 5 items at a time but no luck. Then i opened only 2 url's - 1 as given in the demo app and other one from amazon s3. The 1st one worked very well but no luck with the 2nd one. 

Any tips?

**Comment by Hemant0812** [comment]
i believe the problem is that we are doing the processing i.e. loading images and videos on the main thread, that's why it is hanging the main ui. Let me know

**Comment by Krupen** [comment]
Yes, the processing is indeed on the main thread. But it is only called when the user stops scrolling. After the scrolling ends, it loads the video from the url, hence if the video is big, it will take time to load. 

To achieve even better performance, videos can be downloaded in separate thread in background and stored in local storage. Whenever user scrolls to that item, video will be played from local storage if available. The library does not do it in this way for now but I am trying to figure out how it can be added as a feature in the library.

**Comment by Krupen** [comment]
Hi, I just added the download to local storage feature today. 
Please update to version 0.0.9 to use this feature.
You can find how to use it here https://github.com/Krupen/AutoplayVideos/blob/master/README.md#download-videos-to-local-storage-optional

**Comment by Hemant0812** [comment]
Thanks, Will give it a try

**Comment by Krupen** [comment]
Closing this issue, feel free to reopen if not solved.
