### ISSUE TITLE
Only the first video plays

### ISSUE THREAD

**Issue by IndDev** [Krupen/AutoplayVideos#19]
Hi, 

Thanks for this awesome library. I first checked out your sample app, that worked perfectly.  

I couldnt get it working for my app, also pardon me if I share too much info as I am a newbie to android and not really sure where th issue lies, my app design or the library. My app has the following structure-
SignInActivity->Main nav_drawer activity-> 3 Fragments & 1 activity (VideoActivity).

Case 1: I used the gradle import option and defined the adapter, model and the res files. The video activity loaded. However, only the first video played. 

Case 2: I manually imported the autoplayvideos from the sample app into my app. Then defined the adapter, model and res files. Video activity loaded and ALL videos played.  

Is there some issue with the current version that I got via gradle?

Thanks

**Comment by Krupen** [comment]
did you try ` recyclerView.setPlayOnlyFirstVideo(false);` ?

**Comment by IndDev** [comment]
Yes I did! 

`public class VideosActivity extends AppCompatActivity {

    @BindView(R.id.rv_videos)
    AAH_CustomRecyclerView recyclerView;

    private final List<VideoListItem> urls = new ArrayList<>();

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_videos);
        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);

        FloatingActionButton fab = (FloatingActionButton) findViewById(R.id.fab);
        fab.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Snackbar.make(view, "Replace with your own action", Snackbar.LENGTH_LONG)
                        .setAction("Action", null).show();
            }
        });
        getSupportActionBar().setDisplayHomeAsUpEnabled(true);


        ButterKnife.bind(this);

        Picasso p = Picasso.with(this);
//        urls.add(new VideoListItem("http://www.betcoingaming.com/webdesigns/animatedslider/images/liveroulette2.mp4","http://res.cloudinary.com/krupen/video/upload/w_300,h_150,c_crop,q_70,so_0/v1481795681/2_rp0zyy.jpg","name1"));
        urls.add(new VideoListItem("http://res.cloudinary.com/krupen/video/upload/w_300,h_150,c_crop,q_70/v1481795681/2_rp0zyy.mp4","http://res.cloudinary.com/krupen/video/upload/w_300,h_150,c_crop,q_70,so_0/v1481795681/2_rp0zyy.jpg","video1"));
        urls.add(new VideoListItem("http://res.cloudinary.com/krupen/video/upload/w_300,h_150,c_crop,q_70/v1491561340/hello_cuwgcb.mp4","http://res.cloudinary.com/krupen/video/upload/w_300,h_150,c_crop,q_70,so_0/v1491561340/hello_cuwgcb.jpg","video2"));
        urls.add(new VideoListItem("http://res.cloudinary.com/krupen/image/upload/q_70/v1481795690/3_lfndfq.jpg","image3"));
        urls.add(new VideoListItem("http://res.cloudinary.com/krupen/video/upload/w_300,h_150,c_crop,q_70/v1481795675/3_yqeudi.mp4","http://res.cloudinary.com/krupen/video/upload/w_300,h_150,c_crop,q_70,so_0/v1481795675/3_yqeudi.jpg","video4"));
        urls.add(new VideoListItem("http://res.cloudinary.com/krupen/video/upload/w_300,h_150,c_crop,q_70/v1481795675/1_pyn1fm.mp4","http://res.cloudinary.com/krupen/video/upload/w_300,h_150,c_crop,q_70,so_0/v1481795675/1_pyn1fm.jpg","video5"));
        urls.add(new VideoListItem("http://res.cloudinary.com/krupen/video/upload/w_300,h_150,c_crop,q_70/v1491561340/hello_cuwgcb.mp4","http://res.cloudinary.com/krupen/video/upload/w_300,h_150,c_crop,q_70,so_0/v1491561340/hello_cuwgcb.jpg","video6"));
        urls.add(new VideoListItem("http://res.cloudinary.com/krupen/image/upload/q_70/v1481795690/2_qwpgis.jpg","image7"));
        urls.add(new VideoListItem("http://res.cloudinary.com/krupen/image/upload/q_70/v1481795690/1_ybonak.jpg","image8"));
        urls.add(new VideoListItem("http://res.cloudinary.com/krupen/video/upload/w_300,h_150,c_crop,q_70/v1481795681/2_rp0zyy.mp4","http://res.cloudinary.com/krupen/video/upload/w_300,h_150,c_crop,q_70,so_0/v1481795681/2_rp0zyy.jpg","video9"));
        urls.add(new VideoListItem("http://res.cloudinary.com/krupen/image/upload/q_70/v1481795690/3_lfndfq.jpg","name10"));
        urls.add(new VideoListItem("http://res.cloudinary.com/krupen/video/upload/w_300,h_150,c_crop,q_70/v1481795676/4_nvnzry.mp4","http://res.cloudinary.com/krupen/video/upload/w_300,h_150,c_crop,q_70,so_0/v1481795676/4_nvnzry.jpg","video11"));
        urls.add(new VideoListItem("http://res.cloudinary.com/krupen/video/upload/w_300,h_150,c_crop,q_70/v1481795681/2_rp0zyy.mp4","http://res.cloudinary.com/krupen/video/upload/w_300,h_150,c_crop,q_70,so_0/v1481795681/2_rp0zyy.jpg","video12"));
        urls.add(new VideoListItem("http://res.cloudinary.com/krupen/image/upload/q_70/v1481795690/3_lfndfq.jpg","image13"));
        urls.add(new VideoListItem("http://res.cloudinary.com/krupen/image/upload/q_70/v1481795690/2_qwpgis.jpg","image14"));
        urls.add(new VideoListItem("http://res.cloudinary.com/krupen/video/upload/w_300,h_150,c_crop,q_70/v1481795675/3_yqeudi.mp4","http://res.cloudinary.com/krupen/video/upload/w_300,h_150,c_crop,q_70,so_0/v1481795675/3_yqeudi.jpg","video16"));
        urls.add(new VideoListItem("http://res.cloudinary.com/krupen/image/upload/q_70/v1481795690/1_ybonak.jpg","image15"));
        urls.add(new VideoListItem("http://res.cloudinary.com/krupen/video/upload/w_300,h_150,c_crop,q_70/v1481795675/1_pyn1fm.mp4","http://res.cloudinary.com/krupen/video/upload/w_300,h_150,c_crop,q_70,so_0/v1481795675/1_pyn1fm.jpg","video17"));
        urls.add(new VideoListItem("http://res.cloudinary.com/krupen/video/upload/w_300,h_150,c_crop,q_70/v1481795681/2_rp0zyy.mp4","http://res.cloudinary.com/krupen/video/upload/w_300,h_150,c_crop,q_70,so_0/v1481795681/2_rp0zyy.jpg","video18"));
        urls.add(new VideoListItem("http://res.cloudinary.com/krupen/image/upload/q_70/v1481795690/2_qwpgis.jpg","image19"));
        urls.add(new VideoListItem("http://res.cloudinary.com/krupen/image/upload/q_70/v1481795690/3_lfndfq.jpg","image20"));
        urls.add(new VideoListItem("http://res.cloudinary.com/krupen/image/upload/q_70/v1481795690/1_ybonak.jpg","image21"));


        VideoAdapter mAdapter = new VideoAdapter(urls, p);
        LinearLayoutManager mLayoutManager = new LinearLayoutManager(this);

        recyclerView.setLayoutManager(mLayoutManager);
        recyclerView.setItemAnimator(new DefaultItemAnimator());

        //todo before setAdapter
        recyclerView.setActivity(this);
        //optional
        recyclerView.setPlayOnlyFirstVideo(false); // false by default

        recyclerView.setAdapter(mAdapter);
        //to init videos before scrolling
        recyclerView.smoothScrollBy(0,1);
        recyclerView.smoothScrollBy(0,-1);

    }

}
`

**Comment by IndDev** [comment]
My adapter

```
public class VideoAdapter extends AAH_VideosAdapter{


    private final List<VideoListItem> list;
    private final Picasso picasso;

    public class MyViewHolder extends AAH_CustomViewHolder {

        final TextView tv;
        final ImageView img_vol;

        //to mute/un-mute video (optional)
        boolean isMuted;

        public MyViewHolder(View x) {
            super(x);
            tv = ButterKnife.findById(x, R.id.tv);
            img_vol = ButterKnife.findById(x, R.id.img_vol);
        }

    }

    public VideoAdapter(List<VideoListItem> list_urls, Picasso p) {
        this.list = list_urls;
        this.picasso = p;
    }

    @Override
    public AAH_CustomViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        View itemView = LayoutInflater.from(parent.getContext())
                .inflate(R.layout.video_item, parent, false);
        return new MyViewHolder(itemView);
    }


    @Override
    public void onBindViewHolder(final AAH_CustomViewHolder holder, int position) {
        ((MyViewHolder) holder).tv.setText(list.get(position).getName());

        //todo
        holder.setImageUrl(list.get(position).getImage_url());
        holder.setVideoUrl(list.get(position).getVideo_url());
        //load image into imageview
        if (list.get(position).getImage_url() != null && !list.get(position).getImage_url().isEmpty()) {
            picasso.load(holder.getImageUrl()).config(Bitmap.Config.RGB_565).into(holder.getAAH_ImageView());
        }

        //to mute/un-mute video (optional)
        holder.getAah_vi().setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if (((MyViewHolder) holder).isMuted) {
                    holder.unmuteVideo();
                    ((MyViewHolder) holder).img_vol.setImageResource(R.drawable.ic_unmute);
                } else {
                    holder.muteVideo();
                    ((MyViewHolder) holder).img_vol.setImageResource(R.drawable.ic_mute);
                }
                ((MyViewHolder) holder).isMuted = !((MyViewHolder) holder).isMuted;
            }
        });

        if (list.get(position).getVideo_url()==null){
            ((MyViewHolder) holder).img_vol.setVisibility(View.GONE);
        }else {
            ((MyViewHolder) holder).img_vol.setVisibility(View.VISIBLE);
        }

    }


    @Override
    public int getItemCount() {
        return list.size();
    }


    @Override
    public int getItemViewType(int position) {
        return 0;
    }


}

```

**Comment by Krupen** [comment]
Maybe some issue with gradle import. Try using manually if that is working as per your requirement.

**Comment by Krupen** [comment]
Closing this issue, feel free to  reopen if not solved.
