### ISSUE TITLE
If deleting already downloaded videos, it doesn't downloading again?

### ISSUE THREAD

**Issue by technource-app** [Krupen/AutoplayVideos#22]
Awesome library till day found for playing video with downloading feature but facing minor issue,
I have set setDownloadVideos(true). And now I deleted videos from gallery. Then It is not getting downloaded again. Any solution for this, videos are not shown in gallery or if user deletes any video then It should get downloaded again.

**Comment by Krupen** [comment]
Thank you for appreciating the work, and thank you for pointing out the issue. Just released version 0.1.0 fixing this issue. Update the library version and it should get solved.

**Comment by technource-app** [comment]
Great. Thanks. Will check it and closing issue now.
