### ISSUE TITLE
Play all videos from local storage drive 

### ISSUE THREAD

**Issue by engr-erum** [Krupen/AutoplayVideos#23]
hi how can i load all videos from my local storage of device folder and display list of videos from local storage folder and play it

**Comment by Krupen** [comment]
Hi,
You can do as follows to achieve what you want:
`   

    
    public class MainActivity extends AppCompatActivity {
       private static SharedPreferences sharedPrefs;
       protected static void initialize(Context context) {
        sharedPrefs = PreferenceManager.getDefaultSharedPreferences(context);
       }

       protected static String getString(Context context, String key) {
         if (sharedPrefs == null) {
            initialize(context);
         }
         return sharedPrefs.getString(key, null);
       }

       protected static void saveString(Context context, String key, String value) {
           if (sharedPrefs == null) {
            initialize(context);
           }
           sharedPrefs.edit().putString(key, value).apply();
       }


       @BindView(R.id.rv_home)
       AAH_CustomRecyclerView recyclerView;

       private final List<MyModel> modelList = new ArrayList<>();


       @Override
       protected void onCreate(Bundle savedInstanceState) {
           super.onCreate(savedInstanceState);
           setContentView(R.layout.activity_main);
           ButterKnife.bind(this);

           File dir = new File(Environment.getExternalStorageDirectory() + "/MyVideo");
           File[] listFiles = dir.listFiles();
           if (listFiles!=null){
               List<String> localUrlList = new ArrayList<>();
           for (int i = 0; i < listFiles.length; i++) {
               localUrlList.add(listFiles[i].getAbsolutePath());
               saveString(this,listFiles[i].getAbsolutePath(),listFiles[i].getAbsolutePath());
               modelList.add(new MyModel(listFiles[i].getAbsolutePath(), "<thumbnail>", ""+i));
           
           
           Picasso p = Picasso.with(this);
           MyVideosAdapter mAdapter = new MyVideosAdapter(modelList, p);
           LinearLayoutManager mLayoutManager = new LinearLayoutManager(this);

           recyclerView.setLayoutManager(mLayoutManager);
           recyclerView.setItemAnimator(new DefaultItemAnimator());

           recyclerView.setActivity(this);

           recyclerView.setDownloadPath(Environment.getExternalStorageDirectory() + "/MyVideo"); // (Environment.getExternalStorageDirectory() + "/Video") by default

        recyclerView.setAdapter(mAdapter);
        //to init videos before scrolling
        recyclerView.smoothScrollBy(0, 1);
        recyclerView.smoothScrollBy(0, -1);

           }}`


Replace `Environment.getExternalStorageDirectory() + "/MyVideo"` with your folder path.
Note that `saveString(this,listFiles[i].getAbsolutePath(),listFiles[i].getAbsolutePath());` this line is important.

**Comment by Krupen** [comment]
Closing this for now, feel free to reopen if not solved.
