### ISSUE TITLE
No playback when video URL is not ending with .mp4

### ISSUE THREAD

**Issue by erolasan** [Krupen/AutoplayVideos#24]
Hi,

I am using firebase storage to store my videos, but the download URL it generates its a bit strange looks like this - "https://firebasestorage.googleapis.com/v0/b/predrink-dev.appspot.com/o/EVENT_FEED%2Fvideos%2F-KkKhw9KWq-lsnsXGjPH%2F1496951854596?alt=media&token=7e08cdb4-1a6c-4762-98ef-97bf8a2a7333" - so it doesn't end with .mp4 or any other media type, but the videos are .mp4 and when open the url in the browser the videos work. 

Any idea how can i make this work for your library?
Thanks

**Comment by Krupen** [comment]
Yes, Presently it won't work with video URLs not ending with `.mp4`. But I will add a parameter called `.checkForMp4(false)` (default to true), setting it to false will try to play videos from any URL provided. But developers have to use this with caution and check URLs before passing them to `setVideoUrl()` method. I will be adding this feature soon and will post here again after release.

**Comment by erolasan** [comment]
Ok Thanks! Can you also add callbacks for when the video is buffering and actually playing (to implement a progress bar)?

**Comment by Krupen** [comment]
Hi, I just release an update for making mp4 check optional. Update to version 0.1.1 to make use of it.
```recyclerView.setCheckForMp4(false); // true by default```

For callbacks, it is not so straightforward, but I changed access modifier for method `hideImagePlaceHolder()` hence you can override this method. This method will be called when video is starting to play. In original implementation, it hides the ImageView (thumbnail) and shows CustomVideoView. You can use it to hide ProgressBar, something like below:
```
public class MyViewHolder extends AAH_CustomViewHolder {

        final TextView tv;
        final ImageView img_vol;
        final ProgressBar progressbar;
     
        public MyViewHolder(View x) {
            super(x);
            tv = ButterKnife.findById(x, R.id.tv);
            img_vol = ButterKnife.findById(x, R.id.img_vol);
            progressbar = ButterKnife.findById(x, R.id.pb);
        }

        @Override
        protected void hideImagePlaceHolder() {
            super.hideImagePlaceHolder();
            this.progressbar.setVisibility(View.GONE);
        }
    }
```

Also you can use below method to see if Video is downloaded or not:
```
        boolean isVideoDownloaded = AAH_Utils.isVideoDownloaded(context,url);
```
You can use this to decide whether to show ProgressBar or not.
*This will work only when you have set "setDownloadVideos(true)".

**Comment by Krupen** [comment]
Closing this for now, feel free to re-open if not solved.
