### ISSUE TITLE
Playback doesn't stop

### ISSUE THREAD

**Issue by erolasan** [Krupen/AutoplayVideos#25]
Hi, 
Whenever a video is playing and i minimize the app, the playback doesn't stop an i can hear the sound still playing. Can you fix this please?
Thanks

**Comment by Krupen** [comment]
Sure, will look into it. Thanks for reporting.

**Comment by Krupen** [comment]
Hi, so you can write the below code in MainActivity.java or where you have your RecyclerView: 
```
  @Override
    protected void onStop() {
        super.onStop();
        boolean checkForMp4 = false;
        for (int i = 0; i < modelList.size(); i++) {
            if (recyclerView.findViewHolderForAdapterPosition(i) instanceof AAH_CustomViewHolder) {
                final AAH_CustomViewHolder cvh = (AAH_CustomViewHolder) recyclerView.findViewHolderForAdapterPosition(i);
                if (cvh != null && cvh.getVideoUrl() != null && !cvh.getVideoUrl().equalsIgnoreCase("null") && !cvh.getVideoUrl().isEmpty() && (cvh.getVideoUrl().endsWith(".mp4") || !checkForMp4)) {
                    cvh.pauseVideo();
                }
            }
        }
    }
```

**Comment by erolasan** [comment]
it work!!

Also i used this:

` @Override
    public void onStart() {
        super.onStart();
        boolean checkForMp4 = false;
        for (int i = 0; i < posts.size(); i++) {
            if (recyclerView.findViewHolderForAdapterPosition(i) instanceof AAH_CustomViewHolder) {
                final AAH_CustomViewHolder cvh = (AAH_CustomViewHolder) recyclerView.findViewHolderForAdapterPosition(i);
                if (cvh != null && cvh.getVideoUrl() != null && !cvh.getVideoUrl().equalsIgnoreCase("null") && !cvh.getVideoUrl().isEmpty() && (cvh.getVideoUrl().endsWith(".mp4") || !checkForMp4)) {
                    recyclerView.smoothScrollBy(0,1);
                    recyclerView.smoothScrollBy(0,-1);
                }
            }
        }
    }`
to resume the play when it returns to the app.

Thanks!
