### ISSUE TITLE
Dynamic height

### ISSUE THREAD

**Issue by erolasan** [Krupen/AutoplayVideos#26]
Hi,

I was wondering is there a way to automatically get the height from the video according to its aspect ratio and set it, because now it only works with a fixed height. Is this possible?

Thanks

**Comment by Krupen** [comment]
You can calculate the height of the video and then set it like this: 
```
FrameLayout.LayoutParams lp = new FrameLayout.LayoutParams(<width>, <height>);
holder.getAah_vi().setLayoutParams(lp);
```

**Comment by erolasan** [comment]
This worked, thanks!

**Comment by FranciscoNin** [comment]
But how do you calculate the height?
