### ISSUE TITLE
  How to get percentage of view in adapter 

### ISSUE THREAD

**Issue by drojokef** [Krupen/AutoplayVideos#30]
Hi,
I've try to get  get percentage of view in position of adapter. For example, if percentage is 50  view in position of adapter, then play video. Is there any way to do that?
Thank you.

**Comment by Krupen** [comment]
Hi, currently this is not possible. 
Will consider adding this feature in future version.
It is achievable. For anyone who would like to code it, here is how it can be done:
Change below `if` condition in file `AAH_CustomRecyclerView.java`:
```
 if (rect_parent.contains(rect_child)) {
``` 
Replace this logic with something like below:
```
Rectangle rect_intersect = rect_parent.intersection(rect_child);
int big_area = rect_parent.width()*rect_parent.height();
int small_area = rect_intersect.width()*rect_intersect.height();
int percent = small_area / big_area * 100;
if (percent>50) {
```
If you code it and add it as a feature, feel free to open pull request.

**Comment by Krupen** [comment]
Hi, currently this is not possible. I will consider adding this feature in future versions. 
For now, here is how you might be able to do it:
Replace this `if` condition in file `AAH_CustomRecyclerView.Java`:
```
Rect rect_child = new Rect(location[0], location[1], location[0] + cvh.getAah_vi().getWidth(), location[1] + cvh.getAah_vi().getHeight());
if (rect_parent.contains(rect_child)) {
```
with the following logic:
```
Rect rect_child = new Rect();
cvh.getAah_vi().getGlobalVisibleRect(rect_child);
int big_area = cvh.getAah_vi().getWidth()*cvh.getAah_vi().getHeight();
int small_area = rect_child.width()*rect_child.height();
double div = (double)((double)small_area / (double)big_area);
double percent = (div * 100f);
if (percent>50) {
```

**Comment by drojokef** [comment]
Thank you @Krupen but `percent` gives 100 or 0 when scrolling down.  I hope you ll add this feature in future.
