### ISSUE TITLE
Will this work with FirebaseRecyclerAdapter (FRA)?

### ISSUE THREAD

**Issue by jeremy-jamez** [Krupen/AutoplayVideos#33]
I'm loading images and videos from firebase storage via their download url in the database, will this library work with FRA? I see where you state that the adapter should extend AAH_VideoAdapter but I'm not sure if that can be done with the FRA.
I've tried setting it up like you have done, with the only difference being that the adapter doesn't extend AAH_VideoAdapter. So I'm guessing that's why nothing is being displayed.
I get these errors for each item in the adapter: 
`08-30 20:50:28.959 14942-14942/com.pictematic W/System.err: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.concurrent.Callable.call()' on a null object reference
08-30 20:50:28.960 14942-14942/com.pictematic W/System.err:     at com.allattentionhere.autoplayvideos.AAH_CustomVideoView.onDetachedFromWindow(AAH_CustomVideoView.java:155)
08-30 20:50:28.960 14942-14942/com.pictematic W/System.err:     at android.view.View.dispatchDetachedFromWindow(View.java:15564)
08-30 20:50:28.960 14942-14942/com.pictematic W/System.err:     at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3179)
08-30 20:50:28.960 14942-14942/com.pictematic W/System.err:     at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3179)
08-30 20:50:28.960 14942-14942/com.pictematic W/System.err:     at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3179)
08-30 20:50:28.960 14942-14942/com.pictematic W/System.err:     at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3179)
08-30 20:50:28.960 14942-14942/com.pictematic W/System.err:     at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4715)
08-30 20:50:28.960 14942-14942/com.pictematic W/System.err:     at android.view.ViewGroup.removeViewAt(ViewGroup.java:4665)
08-30 20:50:28.960 14942-14942/com.pictematic W/System.err:     at android.support.v7.widget.RecyclerView$5.removeViewAt(RecyclerView.java:772)
08-30 20:50:28.961 14942-14942/com.pictematic W/System.err:     at android.support.v7.widget.ChildHelper.removeViewAt(ChildHelper.java:168)
08-30 20:50:28.961 14942-14942/com.pictematic W/System.err:     at android.support.v7.widget.RecyclerView$LayoutManager.removeViewAt(RecyclerView.java:8035)
08-30 20:50:28.961 14942-14942/com.pictematic W/System.err:     at android.support.v7.widget.RecyclerView$LayoutManager.removeAndRecycleViewAt(RecyclerView.java:8307)
08-30 20:50:28.961 14942-14942/com.pictematic W/System.err:     at android.support.v7.widget.LinearLayoutManager.recycleChildren(LinearLayoutManager.java:1372)
08-30 20:50:28.961 14942-14942/com.pictematic W/System.err:     at android.support.v7.widget.LinearLayoutManager.recycleViewsFromEnd(LinearLayoutManager.java:1458)
08-30 20:50:28.961 14942-14942/com.pictematic W/System.err:     at android.support.v7.widget.LinearLayoutManager.recycleByLayoutState(LinearLayoutManager.java:1481)
08-30 20:50:28.961 14942-14942/com.pictematic W/System.err:     at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1507)
08-30 20:50:28.961 14942-14942/com.pictematic W/System.err:     at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1330)
08-30 20:50:28.961 14942-14942/com.pictematic W/System.err:     at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1074)
08-30 20:50:28.961 14942-14942/com.pictematic W/System.err:     at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4838)
08-30 20:50:28.961 14942-14942/com.pictematic W/System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
08-30 20:50:28.961 14942-14942/com.pictematic W/System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:686)
08-30 20:50:28.961 14942-14942/com.pictematic W/System.err:     at android.view.Choreographer.doFrame(Choreographer.java:618)
08-30 20:50:28.962 14942-14942/com.pictematic W/System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
08-30 20:50:28.962 14942-14942/com.pictematic W/System.err:     at android.os.Handler.handleCallback(Handler.java:751)
08-30 20:50:28.962 14942-14942/com.pictematic W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
08-30 20:50:28.962 14942-14942/com.pictematic W/System.err:     at android.os.Looper.loop(Looper.java:154)
08-30 20:50:28.962 14942-14942/com.pictematic W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6236)
08-30 20:50:28.962 14942-14942/com.pictematic W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
08-30 20:50:28.962 14942-14942/com.pictematic W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
08-30 20:50:28.962 14942-14942/com.pictematic W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)`

Any ideas on how to fix this?

**Comment by Krupen** [comment]
You will have to extend `AAH_VideoAdapter` for it to work. You can fetch data from Firebase and then store it in List variable and create your own adapter. If you want dynamic updates, set listeners on Firebase database and on update/add/remove items, do those changes in your List variable and call notifyDataSetChanged() on your adapter.

**Comment by Krupen** [comment]
Closing this for now, feel free to re-open if not solved.

**Comment by jeremy-jamez** [comment]
I finally got around to making the changes however the recyclerview shows up blank. No images or videos are loaded. The URLs for the videos and images are from firebase storage.

**MultiViewTypeAdapter:**
```
public class MultiViewTypeAdapter extends AAH_VideosAdapter {

    private ArrayList dataSet;
    List<Posts> postsList;
    GlideApp glideApp;
    Context mContext;
    int total_types;

    public static class VideoTypeViewHolder extends AAH_CustomViewHolder{

        final ImageView img_vol,img_playback;
        boolean isMuted;

        public VideoTypeViewHolder(View itemView) {
            super(itemView);

            img_vol = (ImageView) itemView.findViewById(R.id.img_vol);
            img_playback = (ImageView) itemView.findViewById(R.id.img_playback);
        }

        @Override
        public void videoStarted() {
            super.videoStarted();
            img_playback.setImageResource(R.drawable.ic_pause);
            if (isMuted) {
                muteVideo();
                img_vol.setImageResource(R.drawable.ic_mute);
            } else {
                unmuteVideo();
                img_vol.setImageResource(R.drawable.ic_unmute);
            }
        }
        @Override
        public void pauseVideo() {
            super.pauseVideo();
            img_playback.setImageResource(R.drawable.ic_play_circle);
        }
    }

    public MultiViewTypeAdapter(List<Posts> data, Context context){
        this.postsList = data;
        this.mContext = context;
        //total_types = dataSet.size();
    }

    @Override
    public AAH_CustomViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        View view;
        view = LayoutInflater.from(parent.getContext()).inflate(R.layout.video_feed_item, parent, false);
        return new VideoTypeViewHolder(view);
    }

    @Override
    public void onBindViewHolder(AAH_CustomViewHolder holder, int position) {
        holder.setImageUrl(postsList.get(position).post_img);
        holder.setVideoUrl(postsList.get(position).post_video);

        if(postsList.get(position).post_img != null && !postsList.get(position).post_img.isEmpty()){
            GlideApp.with(mContext)
                    .load(holder.getImageUrl())
                    .into(holder.getAAH_ImageView());
        }

        holder.setLooping(true);

        ((VideoTypeViewHolder)holder).img_playback.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                if (holder.isPlaying()) {
                    holder.pauseVideo();
                    holder.setPaused(true);
                } else {
                    holder.playVideo();
                    holder.setPaused(false);
                }
            }
        });

        ((VideoTypeViewHolder) holder).img_vol.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if (((VideoTypeViewHolder) holder).isMuted) {
                    holder.unmuteVideo();
                    ((VideoTypeViewHolder) holder).img_vol.setImageResource(R.drawable.ic_unmute);
                } else {
                    holder.muteVideo();
                    ((VideoTypeViewHolder) holder).img_vol.setImageResource(R.drawable.ic_mute);
                }
                ((VideoTypeViewHolder) holder).isMuted = !((VideoTypeViewHolder) holder).isMuted;
            }
        });

        if (postsList.get(position).post_img == null) {
            ((VideoTypeViewHolder) holder).img_vol.setVisibility(View.GONE);
            ((VideoTypeViewHolder) holder).img_playback.setVisibility(View.GONE);
        } else {
            ((VideoTypeViewHolder) holder).img_vol.setVisibility(View.VISIBLE);
            ((VideoTypeViewHolder) holder).img_playback.setVisibility(View.VISIBLE);
        }

    }

    @Override
    public int getItemCount() {
        return postsList.size();
    }
}
```

**Firebase Database Query**
```
postsQuery.addChildEventListener(new ChildEventListener() {
            @Override
            public void onChildAdded(DataSnapshot dataSnapshot, String s) {

                Posts posts = dataSnapshot.getValue(Posts.class);
                postsList.add(posts);

                multiViewTypeAdapter = new MultiViewTypeAdapter(postsList, FeedListActivity.this);
                multiViewTypeAdapter.notifyItemInserted(postsList.size());

            }

            @Override
            public void onChildChanged(DataSnapshot dataSnapshot, String s) {
                multiViewTypeAdapter.notifyDataSetChanged();
            }

            @Override
            public void onChildRemoved(DataSnapshot dataSnapshot) {

            }

            @Override
            public void onChildMoved(DataSnapshot dataSnapshot, String s) {

            }

            @Override
            public void onCancelled(DatabaseError databaseError) {
                throw databaseError.toException();
            }
        });


        recyclerView.setActivity(FeedListActivity.this);
        recyclerView.setCheckForMp4(false);

        recyclerView.setAdapter(multiViewTypeAdapter);
```

**Comment by Krupen** [comment]
I think you forgot to do first fetch of the data, or you din't include in the code snippet above. You should be calling `addListenerForSingleValueEvent()` firebase function initially and then set the listener.  

`addChildEventListener()` is only called when there is any insert/delete/update operation on the data.
