### ISSUE TITLE
UI Freezes if preDownload is disabled.

### ISSUE THREAD

**Issue by penumbram** [Krupen/AutoplayVideos#34]
In the example app, if you comment out the following part

`recyclerView.setDownloadPath(Environment.getExternalStorageDirectory() + "/MyVideo");
  recyclerView.setDownloadVideos(true); // false by default`

       `//extra - start downloading all videos in background before loading RecyclerView
       List<String> urls = new ArrayList<>();
       for (MyModel object : modelList) {
           if (object.getVideo_url() != null && object.getVideo_url().contains("http"))
               urls.add(object.getVideo_url());
       }
       recyclerView.preDownload(urls);`

then the UI begins to freeze when a new video cell is scrolled into the screen until the video starts to play.

**Comment by Krupen** [comment]
Hi @penumbram , I tried commenting those lines and running the app in emulator (Nexus 5 on Lollipop), but I did not face any freezing in the UI.
However I did find it freezing when Internet is off, thank you for bringing this up. I will solve this issue and release an update soon.

**Comment by Krupen** [comment]
Hi @penumbram , just released version `0.1.5`. Please update library to get the updates and also don't forget to add `ACCESS_NETWORK_STATE` permission in AndroidManifest.xml. The app should not freeze when not connected to Internet. Let me know if this solves your issue.

**Comment by penumbram** [comment]
Hi @Krupen,

Thanks for your immediate response. This doesn't solve our issue, but I checked the no internet prob and it definitely existed, and your fix seems to solve it well. That's a win, but as I said, the freezing problem is still around. 

The issue is not that perceptible with your example app. [This](http://techslides.com/demos/sample-videos/small.mp4) is the sample video that I'm using. And to be more descriptive, you may observe this behavior if you follow the steps below:

1. Launch the app
2. Wait for your first video to play
3. Scroll to a new position where another cell with another video is visible
4. Immediately after scrolling ends (this must be when your library is loading the video), try to scroll to another position. The UI is unresponsive for seconds (up to 3-4 seconds).

By the way, my team is also trying to come up with a solution. If We do, I'll surely notify you and/or create a pull request.

**Comment by Krupen** [comment]
Thanks @penumbram

**Comment by iffatfatima** [comment]
In `AAH_CustomVideoView.java`, replacing `mMediaPlayer.prepare();` by `mMediaPlayer.prepareAsync();` solves the UI freezing issue.

**Comment by Krupen** [comment]
Hello everyone, been very busy lately. Just released an update and should fix this issue.

@iffatfatima rightly pointed the issue, `onSurfaceTextureAvailable()` was getting called on the Main Thread and hence the `mediaPlayer.prepare()` was also getting called on Main Thread. using `prepareAsync()` was resolving the crash but it sets the priority very low such that the video won't play at all or play very late. Hence the fix was to call this `prepare()` function in background thread. 

Also I had initialisation function in `onDraw()` method of RecyclerView which was a very bad implementation(I tried to make it call only once but seemed like it wasn't working and hence the freezing issue). Hopefully it is fixed, please let me know how it works for you guys.

**Comment by Krupen** [comment]
Also @penumbram , If you decide to not not download videos to local storage, please consider using  video caching to cache the videos. Here is how to do it https://github.com/Krupen/AutoplayVideos#cache-videos-optional

**Comment by Krupen** [comment]
@iffatfatima @penumbram I hope all the issues are resolved. If not, feel free to reopen this issue.

**Comment by lucazin** [comment]
merge: sync_merge("SurfaceTexture-0-2005-4:3", -1, 1011) returned an error: Too many open files (-24)
06-22 08:25:47.980 2005-2068/br.com.oneplace E/Surface: queueBuffer: error queuing buffer to SurfaceTexture, -22
06-22 08:25:47.980 2005-2068/br.com.oneplace W/OpenGLRenderer: swapBuffers encountered EGL error 12299 on 0x73f8e35930, halting rendering...
06-22 08:25:47.988 2005-2005/br.com.oneplace E/ViewRootImpl@940abb[MainActivity]: ViewRootImpl #2 Surface is not valid.
06-22 08:25:48.908 2005-2005/br.com.oneplace E/ViewRootImpl@940abb[MainActivity]: ViewRootImpl #2 Surface is not valid.
06-22 08:25:49.902 2005-2005/br.com.oneplace E/ViewRootImpl@940abb[MainActivity]: ViewRootImpl #2 Surface is not valid.
06-22 08:25:50.915 2005-2005/br.com.oneplace E/ViewRootImpl@940abb[MainActivity]: ViewRootImpl #2 Surface is not valid.
06-22 08:25:51.656 2005-2005/br.com.oneplace D/ViewRootImpl@940abb[MainActivity]: ViewPostImeInputStage processPointer 0
06-22 08:25:51.671 2005-2005/br.com.oneplace E/ViewRootImpl@940abb[MainActivity]: ViewRootImpl #2 Surface is not valid.
06-22 08:25:51.724 2005-2005/br.com.oneplace E/ViewRootImpl@940abb[MainActivity]: ViewRootImpl #2 Surface is not valid.
06-22 08:25:51.737 2005-2005/br.com.oneplace E/ViewRootImpl@940abb[MainActivity]: ViewRootImpl #2 Surface is not valid.

 ashmem_create_region failed for 'indirect ref table': Too many open files
06-22 08:25:52.506 2005-2005/br.com.oneplace W/art: Throwing OutOfMemoryError "Could not allocate JNI Env"
06-22 08:25:52.507 2005-2005/br.com.oneplace E/InputEventReceiver: Exception dispatching input event.
06-22 08:25:52.507 2005-2005/br.com.oneplace E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
06-22 08:25:52.510 2005-2005/br.com.oneplace E/MessageQueue-JNI: java.lang.OutOfMemoryError: Could not allocate JNI Env
                                                                     at java.lang.Thread.nativeCreate(Native Method)
                                                                     at java.lang.Thread.start(Thread.java:731)
                                                                     at com.allattentionhere.autoplayvideos.AAH_CustomRecyclerView.playAvailableVideos(AAH_CustomRecyclerView.java:93)
                                                                     at com.allattentionhere.autoplayvideos.AAH_CustomRecyclerView$1.onScrollStateChanged(AAH_CustomRecyclerView.java:78)
                                                                     at android.support.v7.widget.RecyclerView.dispatchOnScrollStateChanged(RecyclerView.java:4881)
                                                                     at android.support.v7.widget.RecyclerView.setScrollState(RecyclerView.java:1467)
                                                                     at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:3101)
                                                                     at android.view.View.dispatchTouchEvent(View.java:10731)
                                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2859)
                                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2535)
                                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)

Please help me ... i need this library

**Comment by lucazin** [comment]
this happens when i scroll to up and to down
