### ISSUE TITLE
Image Loading

### ISSUE THREAD

**Issue by sundar-malya** [Krupen/AutoplayVideos#39]
1) Whenever i tap on item or scroll the list image become invisible and if last item is image in list then it also become invisible. It will not show images properly. 
2)When first time videos downloading at that time we can't scroll down the list the views stuck in application.

**Comment by Krupen** [comment]
Are you using version 0.1.6? Also are you using VideoCaching Library?

**Comment by sundar-malya** [comment]
I am not using the gradle version. I have implement the demo directly

**Comment by Krupen** [comment]
I just released an update yesterday, so please do a `git pull` if you cloned library before yesterday. It specifically solves the 2nd issue. 

Also let me know if the 1st issue is present in the sample app in the latest version.

**Comment by sundar-malya** [comment]
Thanks, second issue solved but first one remain the same in application after upgrade

**Comment by Krupen** [comment]
Is it there in the sample app? or if possible, can you help me reproduce it so I can find the bug and solve it.

**Comment by sundar-malya** [comment]
public class MyAdapter extends AAH_VideosAdapter {

    private final ArrayList<BusinessModel.Story_Dashboard> businessList;
    private final Picasso picasso;
    private Context mContext;

    public class MyViewHolder extends AAH_CustomViewHolder {
        final ImageView imgVol, imgPlayback;
        final ProgressBar progressBar;
        //to mute/un-mute video (optional)
        boolean isMuted;

        public MyViewHolder(View x) {
            super(x);
            imgVol = ButterKnife.findById(x, R.id.imgVol);
            imgPlayback = ButterKnife.findById(x, R.id.imgPlayback);

            progressBar = ButterKnife.findById(x, R.id.progressBar);
//            progressBar.setVisibility(View.VISIBLE);

        }

        //override this method to get callback when video starts to play
        @Override
        public void videoStarted() {
            super.videoStarted();
//            progressBar.setVisibility(View.GONE);
            imgPlayback.setImageResource(R.mipmap.ic_launcher);
            if (isMuted) {
                muteVideo();
                imgVol.setImageResource(R.mipmap.ic_launcher);
            } else {
                unmuteVideo();
                imgVol.setImageResource(R.mipmap.ic_launcher);
            }
        }

        @Override
        public void pauseVideo() {
            super.pauseVideo();
//            progressBar.setVisibility(View.VISIBLE);
            imgPlayback.setImageResource(R.mipmap.ic_launcher);
        }
    }

    public BusinessAdapter(Context context, ArrayList<BusinessModel.Story_Dashboard> businessList, Picasso p) {
        this.businessList = businessList;
        this.picasso = p;
        this.mContext = context;
    }

    @Override
    public AAH_CustomViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        View itemView = LayoutInflater.from(parent.getContext())
                .inflate(R.layout.adp_business_list, parent, false);
        return new MyViewHolder(itemView);
    }

    @Override
    public void onBindViewHolder(final AAH_CustomViewHolder holder, final int position) {

        final BusinessModel.Story_Dashboard data = businessList.get(position);
//        ((MyViewHolder) holder).progressBar.setVisibility(View.VISIBLE);

        if (data.getStory_image_video_type().equalsIgnoreCase("0")) {
//            data.setStory_image_video_thumbnail(data.getStory_image_video());
            businessList.get(position).setStory_image_video_thumbnail(data.getStory_image_video());
        }

        holder.setImageUrl(data.getStory_image_video_thumbnail());
        holder.setVideoUrl(data.getStory_image_video());

        if (data.getStory_image_video_thumbnail() != null && !data.getStory_image_video_thumbnail().isEmpty()) {
            picasso.load(holder.getImageUrl()).config(Bitmap.Config.RGB_565).into(holder.getAAH_ImageView());
        }

        holder.setLooping(true); //optional - true by default


        //to play pause videos manually (optional)
        ((MyViewHolder) holder).imgPlayback.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if (holder.isPlaying()) {
                    holder.pauseVideo();
                    holder.setPaused(true);
                } else {
                    holder.playVideo();
                    holder.setPaused(false);
                }
            }
        });

        //to mute/un-mute video (optional)
        ((MyViewHolder) holder).imgVol.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if (((MyViewHolder) holder).isMuted) {
                    holder.unmuteVideo();
                    ((MyViewHolder) holder).imgVol.setImageResource(R.mipmap.ic_launcher);
                } else {
                    holder.muteVideo();
                    ((MyViewHolder) holder).imgVol.setImageResource(R.mipmap.ic_launcher);
                }
                ((MyViewHolder) holder).isMuted = !((MyViewHolder) holder).isMuted;
            }
        });

        if (data.getStory_image_video() == null) {
            ((MyViewHolder) holder).imgVol.setVisibility(View.GONE);
            ((MyViewHolder) holder).imgPlayback.setVisibility(View.GONE);
//            ((MyViewHolder) holder).progressBar.setVisibility(View.VISIBLE);
        } else {
            ((MyViewHolder) holder).imgVol.setVisibility(View.GONE);
            ((MyViewHolder) holder).imgPlayback.setVisibility(View.GONE);
//            ((MyViewHolder) holder).progressBar.setVisibility(View.VISIBLE);
        }

    }

    @Override
    public int getItemCount() {
        return businessList.size();
    }


    @Override
    public int getItemViewType(int position) {
        return 0;
    }


}

1) It is not happen in sample app. In my app i used above adapter code

**Comment by Krupen** [comment]
I am not quite sure, but can you try adding `else` for this code:
```
if (data.getStory_image_video_type().equalsIgnoreCase("0")) {
    // data.setStory_image_video_thumbnail(data.getStory_image_video());
    businessList.get(position).setStory_image_video_thumbnail(data.getStory_image_video());
}
else{
    businessList.get(position).setStory_image_video_thumbnail(null);
}
```

**Comment by Krupen** [comment]
I hope it has fixed your issue, please feel free to reopen if you face any issue with library.
