### ISSUE TITLE
Why not to give access to AAH_CustomVideoView's MediaPlayer?

### ISSUE THREAD

**Issue by maxbaldrighi** [Krupen/AutoplayVideos#40]
Hello @Krupen !

**First of all, great job!**
Second of all: I cannot find in your lib any way to access all the functions needed to act on the video itself... And I'm referring to, for example, get the video's current position in order to resume playing it from that position, or get the original width and height of the playing video...
If I'm not mistaken, access to all these features could be granted just with a simple getter to the AAH_CustomVideoView's MediaPlayer instance, right?

Really hope to see those features in the very near future...

**Comment by Krupen** [comment]
Sure thing, din't really think they were needed but added them in the latest release 0.1.7

**Comment by maxbaldrighi** [comment]
Thank you so much, for the fastest release ever!
I'm trying it right now!
