### ISSUE TITLE
Display with non video textview with autoplay 

### ISSUE THREAD

**Issue by firojandev** [Krupen/AutoplayVideos#43]
Hey,
This library working fine. Thanks for sharing this awesome library. 

This library in only work for video playing. Can you help me how can I use different view holder type with your library? E.x
     Recyclerview
               item-1 : video view
               item-2 : Only text view
               item-3: video view
               item-4: Imageview   etc.
that's mean I want to use different type view holder with your library ?

**Comment by Krupen** [comment]
Found the issue, resolved it and released it. Update to version 0.1.9.
I have also updated the sample app with multiple view types.
You need to extend `AAH_CustomViewHolder` from your ViewHolder.
