### ISSUE TITLE
Slider image view

### ISSUE THREAD

**Issue by khopaderahul01** [Krupen/AutoplayVideos#44]
Hey Krupen,
This library is working fine. Thanks for sharing this awesome library.
As per my app requirement i need to add Slider layout for images. 
So how can I add this in your library.
Also where do I add download progress.
Please let me know if you have any suggestion or Idea for this asap.
Thanks.

**Comment by Krupen** [comment]
This will work with any type of recyclerview i.e. Horizontal, Grid, etc 

Unfortunately you cannot show Download progress using this library, but you can disable download options in Library and write your own logic to download videos and play locally. This way you will have control over Download progress.

**Comment by khopaderahul01** [comment]
Okk Thanks.
Also I am using this library in fragment so will this affect on handler thread.

**Comment by Krupen** [comment]
There shouldn't be any issues using it in Fragemnt.

**Comment by khopaderahul01** [comment]
11-02 18:00:59.546 25385-25651/csplsoftware.com.myapplication W/System.err: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
11-02 18:00:59.548 25385-25651/csplsoftware.com.myapplication W/System.err:     at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6556)
11-02 18:00:59.549 25385-25651/csplsoftware.com.myapplication W/System.err:     at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:942)
11-02 18:00:59.549 25385-25651/csplsoftware.com.myapplication W/System.err:     at android.view.ViewGroup.invalidateChild(ViewGroup.java:5093)
11-02 18:00:59.549 25385-25651/csplsoftware.com.myapplication W/System.err:     at android.view.View.invalidateInternal(View.java:12736)
11-02 18:00:59.549 25385-25651/csplsoftware.com.myapplication W/System.err:     at android.view.View.invalidate(View.java:12700)
11-02 18:00:59.549 25385-25651/csplsoftware.com.myapplication W/System.err:     at android.view.View.invalidate(View.java:12684)
11-02 18:00:59.549 25385-25651/csplsoftware.com.myapplication W/System.err:     at android.widget.ImageView.setImageDrawable(ImageView.java:477)
11-02 18:00:59.549 25385-25651/csplsoftware.com.myapplication W/System.err:     at android.support.v7.widget.AppCompatImageHelper.setImageResource(AppCompatImageHelper.java:77)
11-02 18:00:59.549 25385-25651/csplsoftware.com.myapplication W/System.err:     at android.support.v7.widget.AppCompatImageView.setImageResource(AppCompatImageView.java:81)
11-02 18:00:59.549 25385-25651/csplsoftware.com.myapplication W/System.err:     at csplsoftware.com.myapplication.adapters.MyVideosAdapter$MyViewHolder.videoStarted(MyVideosAdapter.java:60)
11-02 18:00:59.549 25385-25651/csplsoftware.com.myapplication W/System.err:     at com.allattentionhere.autoplayvideos.AAH_CustomViewHolder$1.call(AAH_CustomViewHolder.java:51)
11-02 18:00:59.549 25385-25651/csplsoftware.com.myapplication W/System.err:     at com.allattentionhere.autoplayvideos.AAH_CustomViewHolder$1.call(AAH_CustomViewHolder.java:48)
11-02 18:00:59.549 25385-25651/csplsoftware.com.myapplication W/System.err:     at com.allattentionhere.autoplayvideos.AAH_CustomVideoView.startVideo(AAH_CustomVideoView.java:72)
11-02 18:00:59.549 25385-25651/csplsoftware.com.myapplication W/System.err:     at com.allattentionhere.autoplayvideos.AAH_CustomViewHolder.playVideo(AAH_CustomViewHolder.java:32)
11-02 18:00:59.549 25385-25651/csplsoftware.com.myapplication W/System.err:     at com.allattentionhere.autoplayvideos.AAH_CustomRecyclerView$2.run(AAH_CustomRecyclerView.java:132)
11-02 18:00:59.549 25385-25651/csplsoftware.com.myapplication W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
11-02 18:00:59.549 25385-25651/csplsoftware.com.myapplication W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
11-02 18:00:59.549 25385-25651/csplsoftware.com.myapplication W/System.err:     at android.os.Looper.loop(Looper.java:148)
11-02 18:00:59.550 25385-25651/csplsoftware.com.myapplication W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by khopaderahul01** [comment]
kk Thanks bro.
I think this new version will help me.
