### ISSUE TITLE
Want to control  Auto Play Property

### ISSUE THREAD

**Issue by shihabmi7** [Krupen/AutoplayVideos#45]
I am searching auto play property of the videoview, But not find anything. Can you guide me. Where you wrote auto play properties of video view

**Comment by Krupen** [comment]
Auto play is controlled based on visibility, it will be in the file `AAH_CustomRecyclerView.java`.
The playback is controlled by calling methods `playVideo()` and `pauseVideo()` on `AAH_CustomViewHolder`
