### ISSUE TITLE
not working with android 7.0

### ISSUE THREAD

**Issue by kodlayanzi** [Krupen/AutoplayVideos#47]
autoplayVideos library is not working with android 7.0.

can you check it?

**Comment by Krupen** [comment]
Tested it on Emulator running API 24, working fine for me. Can you tell me more what problem you are facing?

**Comment by kodlayanzi** [comment]
it works fine on lg g3 or others.. but i tried on the new huawei p10, i doesnt work

**Comment by Krupen** [comment]
Strange, p10 is on Oreo or Nougat? Any other param in settings which is turned off?

**Comment by iffatfatima** [comment]
I have tested it on Huawei P10 lite with android N and on Nexus 5x with android O (8 and 8.1 beta), works fine on all.

**Comment by Krupen** [comment]
Thank you @iffatfatima , closing this issue for now. Feel free to re-open if issue persists.
