### ISSUE TITLE
 recyclerView.stopVideos();

### ISSUE THREAD

**Issue by khopaderahul01** [Krupen/AutoplayVideos#48]
recyclerView.stopVideos();
not working in fragments.
I have two tabs when I swipe left videos still plays with audio.
I put this in  recyclerView.stopVideos(); in onPause & onStop.
Please let me know the solution for this.

**Comment by Krupen** [comment]
You will need to set OnPageChangeListener on ViewPager to get callbacks when user switches to next viewpager fragment/view. When you get this callback, call stopVideos() on previous Fragment's/View's RecyclerView.

**Comment by Krupen** [comment]
Something like this:
```viewPager.addOnPageChangeListener(new ViewPager.OnPageChangeListener() {
        @Override
        public void onPageScrolled(int position, float positionOffset, int positionOffsetPixels) {

        }

        @Override
        public void onPageSelected(int position) {
             //get all other viewpager fragments and call recyclerView.stopVideos() on all except at this position
        }

        @Override
        public void onPageScrollStateChanged(int state) {

        }
    });
```

**Comment by khopaderahul01** [comment]
Ok Thank you I will try that and let you know.

**Comment by khopaderahul01** [comment]
Its working thanks but I had to make recyclerview static, does it will affect on other things of recyclerview.

**Comment by Krupen** [comment]
It shouldn't, just make sure every static reference is cleared properly when activity is destroyed so that there are no memory leaks.
