### ISSUE TITLE
Is it possible to scale videos (CENTER_CROP)?

### ISSUE THREAD

**Issue by amanzan** [Krupen/AutoplayVideos#51]
I'd like to know if it'd be possible to scale videos, specifically CENTER_CROP to keep the right ratio

**Comment by Krupen** [comment]
You can change the height and width of the `AAH_VideoImage' view by getting it with method `holder.getAah_vi()` in your Adapter.

Video is played on `TextureView`. Android does not support scaling for Videos in TextureView like it does for ImageView. But there might be some way to do it.

**Comment by iffatfatima** [comment]
@amanzan I used matrix transformation to achieve the CENTER _CROP like functionality for video. But it is not a recommended solution to use for recycler view items. You can use this function for that, call it in onVideoSizeChanged() or in onPrepare(), whatever suits your needs: 

    //Center crop on texture view
	private void adjustView(float videoWidth, float videoHeight) {

        if(videoWidth != 0 && videoHeight != 0) {
            float scaleX = 1.0f;
            float scaleY = 1.0f;

            float viewWidth = //set this equal to the width that you want for your video to show in
            float viewHeight = //set this equal to the width that you want for your video to show in
            if(viewWidth != 0 && viewHeight != 0) {
                if (videoWidth > viewWidth && videoHeight > viewHeight) {
                    scaleX = videoWidth / viewWidth;
                    scaleY = videoHeight / viewHeight;
                }
                else if (viewWidth > videoWidth) {
                    scaleY = (viewWidth / videoWidth) / (viewHeight / videoHeight);
                } else if (viewHeight > videoHeight) {
                    scaleX = (viewHeight / videoHeight) / (viewWidth / videoWidth);
                }

                // Calculate pivot points, in this case crop from center
                int pivotPointX = (int)viewWidth / 2;
                int pivotPointY = (int)viewHeight / 2;

                Matrix matrix = new Matrix();
                matrix.setScale(scaleX, scaleY, pivotPointX, pivotPointY);

                this.setTransform(matrix);
                this.setLayoutParams(new FrameLayout.LayoutParams((int)viewWidth, (int)viewHeight));
            }
        }
    }
