### ISSUE TITLE
Avoid restarting video when it goes off and on screen?

### ISSUE THREAD

**Issue by amanzan** [Krupen/AutoplayVideos#52]
Is it possible to do a real pause of the video when it goes off screen, and when it goes on again, resume when it was paused? Right now videos restart from the beginning

**Comment by Krupen** [comment]
Yes, it should be possible. Planning to add that in the next release, will take some time as it is not quite straight forward.

**Comment by Krupen** [comment]
Hi @amanzan , I tried to do what you mentioned above. The problem with this is that you won't have a thumbnail for wherever your seek position is, and you can't keep the MediaPlayer in memory for every video. So doing this won't be possible without keeping every MediaPlayer in memory, or if we just keep seek-position in memory, it will start abruptly from middle as thumbnail is always the first frame. If you can suggest any solution, would be happy to implement. Thanks.

**Comment by amanzan** [comment]
Thanks for looking into it @Krupen . I'd like to test if keeping MediaPlayer in memory do not impact performance too much. How would I do this?

Also, any idea how Instagram handles videos? They seem to pause videos and resume them without any abrupt start.

**Comment by Krupen** [comment]
Instagram does not resume videos if you scroll too much away from it and scroll back to that video quickly. But I believe they must be saving that particular frame in memory as image and when we scroll back, they re-init the mediaPlayer and resume from that position.

**Comment by amanzan** [comment]
Thanks @Krupen.

One last thing, is it possible to keep several videos playing at the same time if they appear on screen? Apparently only one can be playing at the same time

**Comment by Krupen** [comment]
Yes you can play multiple videos at the same time, just don't set 
```
recyclerView.setPlayOnlyFirstVideo(true); 
```
 or set it to `false`.
Please note that the audio will also play simultaneously for all videos.
