### ISSUE TITLE
can we add exoplayer support?

### ISSUE THREAD

**Issue by kodlayanzi** [Krupen/AutoplayVideos#53]
sometimes i am using this codes, videos not appearing on the screen.

exoplayer library is most complicated than default android video stream system.

what do you think?

**Comment by Krupen** [comment]
Hi,
I haven't looked at the usage and benefits of Exoplayer. Will go through those and see if it improves performance when used with this library. 
Also if you can try and integrate exoplayer in this library and check the performance, I would be grateful to merge your pull request.

**Comment by kodlayanzi** [comment]
okey i'll try :)
