### ISSUE TITLE
Uncrop videos

### ISSUE THREAD

**Issue by FranciscoNin** [Krupen/AutoplayVideos#58]
Hi!

I have some videos that were recorded in portait mode, and when playing in other players it shows the whole video with blank spaces on each side. Can I play the videos without cropping them?

Thanks!

**Comment by Krupen** [comment]
Hi,

You can set the height and width of the container by using ` holder.getAah_vi()` in `onBindViewHolder()` method of your adapter. It will return you the parent view which shows the video.

**Comment by Krupen** [comment]
I hope the issue is resolved, it not feel free to re-open this issue.
