### ISSUE TITLE
Add Media controller

### ISSUE THREAD

**Issue by manishdevda** [Krupen/AutoplayVideos#59]
How to add media controller in AutoplayVideo lib?
I fail to integrate video controller and horizontal progress of video duration?
please help with this issue.

**Comment by Krupen** [comment]
Hi,

You can get the MediaPlayer of the video by calling `holder.getAah_vi().getCustomVideoView().getMediaPlayer()` in the Adapter for RecyclerView. You can add any type of controls by using this MediaPlayer instance.

**Comment by Krupen** [comment]
I hope the issue is resolved, it not feel free to re-open this issue.

**Comment by nehapraksh** [comment]
holder.getAah_vi().getCustomVideoView().getMediaPlayer() is giving "null". Please help me get the media player in my adapter.

**Comment by nehapraksh** [comment]
> How to add media controller in AutoplayVideo lib?
> I fail to integrate video controller and horizontal progress of video duration?
> please help with this issue.

Hey,
Did you able to integrate video controller and horizontal progress of video duration? If yes please help me I want the same feature in my app.

**Comment by yoonusc** [comment]
same
