### ISSUE TITLE
Video not play

### ISSUE THREAD

**Issue by sivasonai** [Krupen/AutoplayVideos#60]
Hi Krupen,

Video not play automatically and manually, I have the API that contain first 4 pages only image after that one video is come that video not play automatically and click play button  also.
  
  this.getSurfaceTexture() is return null

**Comment by Krupen** [comment]
Hi,
Are you using RecyclerView? I need to see some code to be able to find the problem.

**Comment by Krupen** [comment]
I hope the issue is resolved, if not feel free to re-open this issue.

**Comment by yoonusc** [comment]
getting this issue did you fixed it ?
