### ISSUE TITLE
Recyclerview item position inter change

### ISSUE THREAD

**Issue by sundar-malya** [Krupen/AutoplayVideos#61]
When i am scrolling recyclerview at that time last position video visible on first position ? How can i resolve it , I also put every if else condition properly still got this issue

**Comment by Krupen** [comment]
Hi, 
This seems pretty strange. For debugging, can you try using just images and see if issue still persists. If yes then maybe some problem with your RecyclerView Adapter implementation, if not, please share some sample code so I can have a look.

**Comment by Krupen** [comment]
I hope the issue is resolved, if not feel free to re-open this issue.
