### ISSUE TITLE
Only direct video link with mp4 extension is working

### ISSUE THREAD

**Issue by anandhkumar25** [Krupen/AutoplayVideos#63]
when I give the direct link like https://firebasestorage.googleapis.com/v0/b/flickering-heat-5334.appspot.com/o/demo1.mp4?.....,this link is working in autoplay, but when I give the other extension like mov,it doesn't work.
Please help.

Thankyou.

**Comment by Krupen** [comment]
Hi,
Please try setting ` recyclerView.setCheckForMp4(false);`. If it still doesn't work, default MediaPlayer might not be supporting that video type and hence it won't work with this library.
